# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bdm_unified_large.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BDMUnifiedFormLarge(object):
    def setupUi(self, BDMUnifiedFormLarge):
        BDMUnifiedFormLarge.setObjectName("BDMUnifiedFormLarge")
        BDMUnifiedFormLarge.resize(1185, 677)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        BDMUnifiedFormLarge.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(BDMUnifiedFormLarge)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 711, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.previewLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.previewLayout.setContentsMargins(0, 0, 0, 0)
        self.previewLayout.setSpacing(6)
        self.previewLayout.setObjectName("previewLayout")
        self.camSwtchLayout = QtWidgets.QHBoxLayout()
        self.camSwtchLayout.setObjectName("camSwtchLayout")
        self.rdBtnIP = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rdBtnIP.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdBtnIP.sizePolicy().hasHeightForWidth())
        self.rdBtnIP.setSizePolicy(sizePolicy)
        self.rdBtnIP.setStyleSheet("")
        self.rdBtnIP.setChecked(True)
        self.rdBtnIP.setObjectName("rdBtnIP")
        self.camSwtchLayout.addWidget(self.rdBtnIP)
        self.rdBtnFP = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rdBtnFP.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdBtnFP.sizePolicy().hasHeightForWidth())
        self.rdBtnFP.setSizePolicy(sizePolicy)
        self.rdBtnFP.setMinimumSize(QtCore.QSize(0, 0))
        self.rdBtnFP.setObjectName("rdBtnFP")
        self.camSwtchLayout.addWidget(self.rdBtnFP)
        self.previewLayout.addLayout(self.camSwtchLayout)
        self.matplotlibLayout = QtWidgets.QHBoxLayout()
        self.matplotlibLayout.setObjectName("matplotlibLayout")
        self.plotArea = MPLCanvas(self.verticalLayoutWidget)
        self.plotArea.setObjectName("plotArea")
        self.matplotlibLayout.addWidget(self.plotArea)
        self.previewLayout.addLayout(self.matplotlibLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fpMinValTipLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpMinValTipLbl.setEnabled(False)
        self.fpMinValTipLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpMinValTipLbl.setObjectName("fpMinValTipLbl")
        self.horizontalLayout.addWidget(self.fpMinValTipLbl)
        self.fpMinValLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpMinValLbl.setEnabled(False)
        self.fpMinValLbl.setText("")
        self.fpMinValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpMinValLbl.setObjectName("fpMinValLbl")
        self.horizontalLayout.addWidget(self.fpMinValLbl)
        self.fpMaxValTipLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpMaxValTipLbl.setEnabled(False)
        self.fpMaxValTipLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpMaxValTipLbl.setObjectName("fpMaxValTipLbl")
        self.horizontalLayout.addWidget(self.fpMaxValTipLbl)
        self.fpMaxValLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpMaxValLbl.setEnabled(False)
        self.fpMaxValLbl.setText("")
        self.fpMaxValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpMaxValLbl.setObjectName("fpMaxValLbl")
        self.horizontalLayout.addWidget(self.fpMaxValLbl)
        self.fpSatValTipLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpSatValTipLbl.setEnabled(False)
        self.fpSatValTipLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpSatValTipLbl.setObjectName("fpSatValTipLbl")
        self.horizontalLayout.addWidget(self.fpSatValTipLbl)
        self.fpSatValLbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpSatValLbl.setEnabled(False)
        self.fpSatValLbl.setText("")
        self.fpSatValLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fpSatValLbl.setObjectName("fpSatValLbl")
        self.horizontalLayout.addWidget(self.fpSatValLbl)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.previewLayout.addLayout(self.horizontalLayout)
        self.fpOptionLayout = QtWidgets.QHBoxLayout()
        self.fpOptionLayout.setObjectName("fpOptionLayout")
        self.showHologramChkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.showHologramChkbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showHologramChkbox.sizePolicy().hasHeightForWidth())
        self.showHologramChkbox.setSizePolicy(sizePolicy)
        self.showHologramChkbox.setObjectName("showHologramChkbox")
        self.fpOptionLayout.addWidget(self.showHologramChkbox)
        self.showFFTChkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.showFFTChkbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showFFTChkbox.sizePolicy().hasHeightForWidth())
        self.showFFTChkbox.setSizePolicy(sizePolicy)
        self.showFFTChkbox.setObjectName("showFFTChkbox")
        self.fpOptionLayout.addWidget(self.showFFTChkbox)
        self.showCroppedChkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.showCroppedChkbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showCroppedChkbox.sizePolicy().hasHeightForWidth())
        self.showCroppedChkbox.setSizePolicy(sizePolicy)
        self.showCroppedChkbox.setChecked(True)
        self.showCroppedChkbox.setObjectName("showCroppedChkbox")
        self.fpOptionLayout.addWidget(self.showCroppedChkbox)
        self.fpOptionSprtr = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.fpOptionSprtr.setFrameShape(QtWidgets.QFrame.VLine)
        self.fpOptionSprtr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.fpOptionSprtr.setObjectName("fpOptionSprtr")
        self.fpOptionLayout.addWidget(self.fpOptionSprtr)
        self.useGPUChkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.useGPUChkbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useGPUChkbox.sizePolicy().hasHeightForWidth())
        self.useGPUChkbox.setSizePolicy(sizePolicy)
        self.useGPUChkbox.setChecked(True)
        self.useGPUChkbox.setObjectName("useGPUChkbox")
        self.fpOptionLayout.addWidget(self.useGPUChkbox)
        self.gaussBlurChkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.gaussBlurChkbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaussBlurChkbox.sizePolicy().hasHeightForWidth())
        self.gaussBlurChkbox.setSizePolicy(sizePolicy)
        self.gaussBlurChkbox.setObjectName("gaussBlurChkbox")
        self.fpOptionLayout.addWidget(self.gaussBlurChkbox)
        self.previewLayout.addLayout(self.fpOptionLayout)
        self.camCtrlLayout = QtWidgets.QHBoxLayout()
        self.camCtrlLayout.setObjectName("camCtrlLayout")
        self.btnStrt = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStrt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStrt.sizePolicy().hasHeightForWidth())
        self.btnStrt.setSizePolicy(sizePolicy)
        self.btnStrt.setObjectName("btnStrt")
        self.camCtrlLayout.addWidget(self.btnStrt)
        self.btnStop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnStop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setObjectName("btnStop")
        self.camCtrlLayout.addWidget(self.btnStop)
        self.camCtrlSprtr = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.camCtrlSprtr.setFrameShape(QtWidgets.QFrame.VLine)
        self.camCtrlSprtr.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.camCtrlSprtr.setObjectName("camCtrlSprtr")
        self.camCtrlLayout.addWidget(self.camCtrlSprtr)
        self.edtSaveFilename = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edtSaveFilename.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtSaveFilename.sizePolicy().hasHeightForWidth())
        self.edtSaveFilename.setSizePolicy(sizePolicy)
        self.edtSaveFilename.setObjectName("edtSaveFilename")
        self.camCtrlLayout.addWidget(self.edtSaveFilename)
        self.lblTiffTxt = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblTiffTxt.setEnabled(False)
        self.lblTiffTxt.setObjectName("lblTiffTxt")
        self.camCtrlLayout.addWidget(self.lblTiffTxt)
        self.btnSaveImg = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSaveImg.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveImg.sizePolicy().hasHeightForWidth())
        self.btnSaveImg.setSizePolicy(sizePolicy)
        self.btnSaveImg.setObjectName("btnSaveImg")
        self.camCtrlLayout.addWidget(self.btnSaveImg)
        self.camCtrlLayout.setStretch(0, 2)
        self.camCtrlLayout.setStretch(1, 2)
        self.camCtrlLayout.setStretch(2, 1)
        self.camCtrlLayout.setStretch(3, 2)
        self.camCtrlLayout.setStretch(5, 2)
        self.previewLayout.addLayout(self.camCtrlLayout)
        self.previewLayout.setStretch(0, 1)
        self.previewLayout.setStretch(1, 16)
        self.previewLayout.setStretch(2, 1)
        self.previewLayout.setStretch(3, 2)
        self.previewLayout.setStretch(4, 2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(BDMUnifiedFormLarge)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(740, 10, 431, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mcLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mcLayout.setContentsMargins(0, 0, 0, 0)
        self.mcLayout.setObjectName("mcLayout")
        self.mcAxWidget = QAxContainer.QAxWidget(self.verticalLayoutWidget_2)
        self.mcAxWidget.setObjectName("mcAxWidget")
        self.mcLayout.addWidget(self.mcAxWidget)
        self.mcCtrlLayout = QtWidgets.QGridLayout()
        self.mcCtrlLayout.setObjectName("mcCtrlLayout")
        self.btnMCN01 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnMCN01.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMCN01.sizePolicy().hasHeightForWidth())
        self.btnMCN01.setSizePolicy(sizePolicy)
        self.btnMCN01.setObjectName("btnMCN01")
        self.mcCtrlLayout.addWidget(self.btnMCN01, 0, 0, 1, 1)
        self.btnMCN003 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnMCN003.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMCN003.sizePolicy().hasHeightForWidth())
        self.btnMCN003.setSizePolicy(sizePolicy)
        self.btnMCN003.setObjectName("btnMCN003")
        self.mcCtrlLayout.addWidget(self.btnMCN003, 0, 1, 1, 1)
        self.btnMCP01 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnMCP01.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMCP01.sizePolicy().hasHeightForWidth())
        self.btnMCP01.setSizePolicy(sizePolicy)
        self.btnMCP01.setObjectName("btnMCP01")
        self.mcCtrlLayout.addWidget(self.btnMCP01, 0, 3, 1, 1)
        self.btnMCP003 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnMCP003.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMCP003.sizePolicy().hasHeightForWidth())
        self.btnMCP003.setSizePolicy(sizePolicy)
        self.btnMCP003.setObjectName("btnMCP003")
        self.mcCtrlLayout.addWidget(self.btnMCP003, 0, 2, 1, 1)
        self.mcCtrlLayout.setColumnStretch(0, 1)
        self.mcCtrlLayout.setColumnStretch(1, 1)
        self.mcCtrlLayout.setColumnStretch(2, 1)
        self.mcCtrlLayout.setColumnStretch(3, 1)
        self.mcLayout.addLayout(self.mcCtrlLayout)
        self.mcLayout.setStretch(0, 3)
        self.mcLayout.setStretch(1, 1)
        self.ctrlTabs = QtWidgets.QTabWidget(BDMUnifiedFormLarge)
        self.ctrlTabs.setEnabled(True)
        self.ctrlTabs.setGeometry(QtCore.QRect(740, 300, 431, 361))
        self.ctrlTabs.setObjectName("ctrlTabs")
        self.TabExp = QtWidgets.QWidget()
        self.TabExp.setObjectName("TabExp")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.TabExp)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 401, 301))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.ctrlLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.ctrlLayout.setContentsMargins(0, 0, 0, 0)
        self.ctrlLayout.setObjectName("ctrlLayout")
        self.lblCtrlSmplNo = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlSmplNo.setEnabled(False)
        self.lblCtrlSmplNo.setObjectName("lblCtrlSmplNo")
        self.ctrlLayout.addWidget(self.lblCtrlSmplNo, 2, 0, 1, 1)
        self.lblCtrlInf = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlInf.setEnabled(False)
        self.lblCtrlInf.setObjectName("lblCtrlInf")
        self.ctrlLayout.addWidget(self.lblCtrlInf, 1, 0, 1, 1)
        self.lblCtrlSts = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlSts.setEnabled(False)
        self.lblCtrlSts.setObjectName("lblCtrlSts")
        self.ctrlLayout.addWidget(self.lblCtrlSts, 0, 0, 1, 1)
        self.ctrlSmpNospinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.ctrlSmpNospinBox.setEnabled(False)
        self.ctrlSmpNospinBox.setMinimum(1)
        self.ctrlSmpNospinBox.setMaximum(1000)
        self.ctrlSmpNospinBox.setObjectName("ctrlSmpNospinBox")
        self.ctrlLayout.addWidget(self.ctrlSmpNospinBox, 2, 1, 1, 1)
        self.lblCtrlEndTime = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlEndTime.setEnabled(False)
        self.lblCtrlEndTime.setObjectName("lblCtrlEndTime")
        self.ctrlLayout.addWidget(self.lblCtrlEndTime, 5, 0, 1, 1)
        self.btnCtrlStrt = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCtrlStrt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCtrlStrt.sizePolicy().hasHeightForWidth())
        self.btnCtrlStrt.setSizePolicy(sizePolicy)
        self.btnCtrlStrt.setObjectName("btnCtrlStrt")
        self.ctrlLayout.addWidget(self.btnCtrlStrt, 3, 0, 1, 2)
        self.lblCtrlStrtTime = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlStrtTime.setEnabled(False)
        self.lblCtrlStrtTime.setObjectName("lblCtrlStrtTime")
        self.ctrlLayout.addWidget(self.lblCtrlStrtTime, 4, 0, 1, 1)
        self.lblCtrlEndTimeTxt = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlEndTimeTxt.setEnabled(False)
        self.lblCtrlEndTimeTxt.setText("")
        self.lblCtrlEndTimeTxt.setObjectName("lblCtrlEndTimeTxt")
        self.ctrlLayout.addWidget(self.lblCtrlEndTimeTxt, 5, 1, 1, 3)
        self.btnCtrlHlt = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCtrlHlt.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCtrlHlt.sizePolicy().hasHeightForWidth())
        self.btnCtrlHlt.setSizePolicy(sizePolicy)
        self.btnCtrlHlt.setObjectName("btnCtrlHlt")
        self.ctrlLayout.addWidget(self.btnCtrlHlt, 3, 2, 1, 2)
        self.lblCtrlInfText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlInfText.setEnabled(False)
        self.lblCtrlInfText.setText("")
        self.lblCtrlInfText.setObjectName("lblCtrlInfText")
        self.ctrlLayout.addWidget(self.lblCtrlInfText, 1, 1, 1, 3)
        self.lblCtrlStrtTimeTxt = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlStrtTimeTxt.setEnabled(False)
        self.lblCtrlStrtTimeTxt.setText("")
        self.lblCtrlStrtTimeTxt.setObjectName("lblCtrlStrtTimeTxt")
        self.ctrlLayout.addWidget(self.lblCtrlStrtTimeTxt, 4, 1, 1, 3)
        self.monitorOffChkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.monitorOffChkbox.setEnabled(False)
        self.monitorOffChkbox.setChecked(True)
        self.monitorOffChkbox.setObjectName("monitorOffChkbox")
        self.ctrlLayout.addWidget(self.monitorOffChkbox, 2, 2, 1, 2)
        self.lblCtrlStsText = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lblCtrlStsText.setEnabled(False)
        self.lblCtrlStsText.setText("")
        self.lblCtrlStsText.setObjectName("lblCtrlStsText")
        self.ctrlLayout.addWidget(self.lblCtrlStsText, 0, 1, 1, 3)
        self.ctrlLayout.setColumnStretch(0, 1)
        self.ctrlLayout.setColumnStretch(1, 1)
        self.ctrlLayout.setColumnStretch(2, 1)
        self.ctrlLayout.setColumnStretch(3, 1)
        self.ctrlLayout.setRowStretch(0, 1)
        self.ctrlLayout.setRowStretch(1, 1)
        self.ctrlLayout.setRowStretch(2, 1)
        self.ctrlLayout.setRowStretch(3, 2)
        self.ctrlLayout.setRowStretch(4, 1)
        self.ctrlLayout.setRowStretch(5, 1)
        self.ctrlTabs.addTab(self.TabExp, "")
        self.tabDevices = QtWidgets.QWidget()
        self.tabDevices.setObjectName("tabDevices")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabDevices)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 401, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lmpLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lmpLayout.setContentsMargins(0, 0, 0, 0)
        self.lmpLayout.setObjectName("lmpLayout")
        self.btnLmpOn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLmpOn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLmpOn.sizePolicy().hasHeightForWidth())
        self.btnLmpOn.setSizePolicy(sizePolicy)
        self.btnLmpOn.setObjectName("btnLmpOn")
        self.lmpLayout.addWidget(self.btnLmpOn, 0, 1, 1, 1)
        self.btnLmpOff = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLmpOff.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLmpOff.sizePolicy().hasHeightForWidth())
        self.btnLmpOff.setSizePolicy(sizePolicy)
        self.btnLmpOff.setObjectName("btnLmpOff")
        self.lmpLayout.addWidget(self.btnLmpOff, 0, 2, 1, 1)
        self.lblLamp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblLamp.setEnabled(False)
        self.lblLamp.setObjectName("lblLamp")
        self.lmpLayout.addWidget(self.lblLamp, 0, 0, 1, 1)
        self.lmpLayout.setColumnStretch(0, 1)
        self.lmpLayout.setColumnStretch(1, 1)
        self.lmpLayout.setColumnStretch(2, 1)
        self.lmpLayout.setRowStretch(0, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabDevices)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 401, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.sldLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.sldLayout.setContentsMargins(0, 0, 0, 0)
        self.sldLayout.setObjectName("sldLayout")
        self.lblSLDHIOutputTxt = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblSLDHIOutputTxt.setEnabled(False)
        self.lblSLDHIOutputTxt.setText("")
        self.lblSLDHIOutputTxt.setObjectName("lblSLDHIOutputTxt")
        self.sldLayout.addWidget(self.lblSLDHIOutputTxt, 1, 1, 1, 1)
        self.btnSLDChkSts = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnSLDChkSts.setEnabled(False)
        self.btnSLDChkSts.setObjectName("btnSLDChkSts")
        self.sldLayout.addWidget(self.btnSLDChkSts, 2, 0, 1, 1)
        self.lblSLDPower = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblSLDPower.setEnabled(False)
        self.lblSLDPower.setObjectName("lblSLDPower")
        self.sldLayout.addWidget(self.lblSLDPower, 1, 2, 1, 1)
        self.lblSLDHIOutput = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblSLDHIOutput.setEnabled(False)
        self.lblSLDHIOutput.setObjectName("lblSLDHIOutput")
        self.sldLayout.addWidget(self.lblSLDHIOutput, 1, 0, 1, 1)
        self.lblSLD = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblSLD.setEnabled(False)
        self.lblSLD.setObjectName("lblSLD")
        self.sldLayout.addWidget(self.lblSLD, 0, 0, 1, 1)
        self.lblSLDPowerTxt = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblSLDPowerTxt.setEnabled(False)
        self.lblSLDPowerTxt.setText("")
        self.lblSLDPowerTxt.setObjectName("lblSLDPowerTxt")
        self.sldLayout.addWidget(self.lblSLDPowerTxt, 1, 3, 1, 1)
        self.btnSLDSetHION = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnSLDSetHION.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSLDSetHION.sizePolicy().hasHeightForWidth())
        self.btnSLDSetHION.setSizePolicy(sizePolicy)
        self.btnSLDSetHION.setObjectName("btnSLDSetHION")
        self.sldLayout.addWidget(self.btnSLDSetHION, 2, 1, 2, 2)
        self.btnSLDSwtchHI = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnSLDSwtchHI.setEnabled(False)
        self.btnSLDSwtchHI.setObjectName("btnSLDSwtchHI")
        self.sldLayout.addWidget(self.btnSLDSwtchHI, 3, 0, 1, 1)
        self.btnSLDSwtchPower = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnSLDSwtchPower.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSLDSwtchPower.sizePolicy().hasHeightForWidth())
        self.btnSLDSwtchPower.setSizePolicy(sizePolicy)
        self.btnSLDSwtchPower.setObjectName("btnSLDSwtchPower")
        self.sldLayout.addWidget(self.btnSLDSwtchPower, 2, 3, 2, 1)
        self.sldLayout.setColumnStretch(0, 1)
        self.sldLayout.setColumnStretch(1, 1)
        self.sldLayout.setColumnStretch(2, 1)
        self.sldLayout.setColumnStretch(3, 1)
        self.sldLayout.setRowStretch(0, 1)
        self.sldLayout.setRowStretch(1, 1)
        self.sldLayout.setRowStretch(2, 1)
        self.sldLayout.setRowStretch(3, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabDevices)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.enableCtrlLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.enableCtrlLayout.setContentsMargins(0, 0, 0, 0)
        self.enableCtrlLayout.setObjectName("enableCtrlLayout")
        self.btnEnableAll = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEnableAll.sizePolicy().hasHeightForWidth())
        self.btnEnableAll.setSizePolicy(sizePolicy)
        self.btnEnableAll.setObjectName("btnEnableAll")
        self.enableCtrlLayout.addWidget(self.btnEnableAll)
        self.btnDisableAll = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDisableAll.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisableAll.sizePolicy().hasHeightForWidth())
        self.btnDisableAll.setSizePolicy(sizePolicy)
        self.btnDisableAll.setObjectName("btnDisableAll")
        self.enableCtrlLayout.addWidget(self.btnDisableAll)
        self.ctrlTabs.addTab(self.tabDevices, "")

        self.retranslateUi(BDMUnifiedFormLarge)
        self.ctrlTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BDMUnifiedFormLarge)

    def retranslateUi(self, BDMUnifiedFormLarge):
        _translate = QtCore.QCoreApplication.translate
        BDMUnifiedFormLarge.setWindowTitle(_translate("BDMUnifiedFormLarge", "pyBDIPreview"))
        self.rdBtnIP.setText(_translate("BDMUnifiedFormLarge", "Image Plane (Microscope)"))
        self.rdBtnFP.setText(_translate("BDMUnifiedFormLarge", "Fourier Plane (BDI)"))
        self.fpMinValTipLbl.setText(_translate("BDMUnifiedFormLarge", "Min:"))
        self.fpMaxValTipLbl.setText(_translate("BDMUnifiedFormLarge", "Max:"))
        self.fpSatValTipLbl.setText(_translate("BDMUnifiedFormLarge", "Saturation:"))
        self.showHologramChkbox.setText(_translate("BDMUnifiedFormLarge", "Hologram"))
        self.showFFTChkbox.setText(_translate("BDMUnifiedFormLarge", " FFT"))
        self.showCroppedChkbox.setText(_translate("BDMUnifiedFormLarge", "Cropped"))
        self.useGPUChkbox.setText(_translate("BDMUnifiedFormLarge", "GPU"))
        self.gaussBlurChkbox.setText(_translate("BDMUnifiedFormLarge", "Gaussian"))
        self.btnStrt.setText(_translate("BDMUnifiedFormLarge", "&Start"))
        self.btnStop.setText(_translate("BDMUnifiedFormLarge", "S&top"))
        self.lblTiffTxt.setText(_translate("BDMUnifiedFormLarge", ".tiff"))
        self.btnSaveImg.setText(_translate("BDMUnifiedFormLarge", "Save"))
        self.btnMCN01.setText(_translate("BDMUnifiedFormLarge", "-0.1"))
        self.btnMCN003.setText(_translate("BDMUnifiedFormLarge", "-0.03"))
        self.btnMCP01.setText(_translate("BDMUnifiedFormLarge", "+0.1"))
        self.btnMCP003.setText(_translate("BDMUnifiedFormLarge", "+0.03"))
        self.lblCtrlSmplNo.setText(_translate("BDMUnifiedFormLarge", "No."))
        self.lblCtrlInf.setText(_translate("BDMUnifiedFormLarge", "Info"))
        self.lblCtrlSts.setText(_translate("BDMUnifiedFormLarge", "Status"))
        self.lblCtrlEndTime.setText(_translate("BDMUnifiedFormLarge", "Ended"))
        self.btnCtrlStrt.setText(_translate("BDMUnifiedFormLarge", "Start"))
        self.lblCtrlStrtTime.setText(_translate("BDMUnifiedFormLarge", "Started"))
        self.btnCtrlHlt.setText(_translate("BDMUnifiedFormLarge", "Halt"))
        self.monitorOffChkbox.setText(_translate("BDMUnifiedFormLarge", "Monitor off"))
        self.ctrlTabs.setTabText(self.ctrlTabs.indexOf(self.TabExp), _translate("BDMUnifiedFormLarge", "Exp"))
        self.btnLmpOn.setText(_translate("BDMUnifiedFormLarge", "ON"))
        self.btnLmpOff.setText(_translate("BDMUnifiedFormLarge", "OFF"))
        self.lblLamp.setText(_translate("BDMUnifiedFormLarge", "Lamp"))
        self.btnSLDChkSts.setText(_translate("BDMUnifiedFormLarge", "Check"))
        self.lblSLDPower.setText(_translate("BDMUnifiedFormLarge", "Power:"))
        self.lblSLDHIOutput.setText(_translate("BDMUnifiedFormLarge", "HI:"))
        self.lblSLD.setText(_translate("BDMUnifiedFormLarge", "SLD"))
        self.btnSLDSetHION.setText(_translate("BDMUnifiedFormLarge", "Set\n"
"HI/ON"))
        self.btnSLDSwtchHI.setText(_translate("BDMUnifiedFormLarge", "Switch HI"))
        self.btnSLDSwtchPower.setText(_translate("BDMUnifiedFormLarge", "Switch\n"
"Power"))
        self.btnEnableAll.setText(_translate("BDMUnifiedFormLarge", "Enable"))
        self.btnDisableAll.setText(_translate("BDMUnifiedFormLarge", "Disable"))
        self.ctrlTabs.setTabText(self.ctrlTabs.indexOf(self.tabDevices), _translate("BDMUnifiedFormLarge", "Devices"))


from PyQt5 import QAxContainer
from mplcanvas import MPLCanvas
